language: ruby
install:
- gem install bundler
- bundle install
branches:
  only:
  - source
script:
- bundle exec jekyll build
- ./deploy.sh
notifications:
  email: false
before_install:
    - >- openssl aes-256-cbc -K $encrypted_f6748e572ec7_key -iv $encrypted_f6748e572ec7_iv -in .deploy_key.enc -out .deploy_key -d
    - chmod 0600 .deploy_key
    - eval $(ssh-agent -s)
    - ssh-add .deploy_key